### ISSUE TITLE
PV Opt tile flashes, requires restart of appdaemon to resolve

### ISSUE THREAD

**Issue by ThomasPrior** [stevebuk1/pv_opt#388]
**Describe the bug**

The PV Opt tile will flash in HomeAssistant. This happen about once every 24/48 hours and requires a restart of AppDaemon to resolve temporarily. 

Seems to be correlated with the appearance of the following error:

```
00:39:10 WARNING pv_opt: ------------------------------------------------------------
Exception: Unable to get expected response from Inverter Controller for {self.inverter_type}
raise Exception(e)
File "/conf/apps/pv_opt/pv_opt.py", line 605, in initialize
return f(*args, **kw)
File "/usr/local/lib/python3.10/site-packages/appdaemon/adbase.py", line 35, in f_app_lock
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
response = future.result()
File "/usr/local/lib/python3.10/site-packages/appdaemon/utils.py", line 304, in run_in_executor
await utils.run_in_executor(self, init)
File "/usr/local/lib/python3.10/site-packages/appdaemon/app_management.py", line 162, in initialize_app
00:39:10 WARNING pv_opt: Traceback (most recent call last):
00:39:10 WARNING pv_opt: ------------------------------------------------------------
00:39:10 WARNING pv_opt: Unexpected error running initialize() for pv_opt
00:39:10 WARNING pv_opt: ------------------------------------------------------------
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Wait 24/48 hours
2. Observe flashing tile

**Expected behavior**
No flashing tiles, PV Opt to not require a regular reboot stay running

**Screenshots**

https://github.com/user-attachments/assets/0c5c7bc8-39b0-4626-9c0a-6206e0fecc1d

**Setup**

Running on a Synology NAS in Docker, same Docker network:
- AppDaemon v4.4.2
- HomeAssistant 2025.1.0
- PV Opt v4.08 via HACS

**Additional context**
Tariff: Octopus Go (8.5p 00:30 to 05:30 UTC daily)
Inverter: Solis S5-EH1P5K-L
Connection: Modbus over Ethernet via https://github.com/alienatedsec/solis-ha-modbus-cloud

**Logs**
[pv_opt.log](https://github.com/user-attachments/files/18724696/pv_opt.log)

[error.log](https://github.com/user-attachments/files/18724700/error.log)

**Comment by ThomasPrior** [comment]
https://github.com/user-attachments/assets/037736a3-32ea-4e9e-a777-82826c60631d

This one didn't even wait 24 hours :)


[pv_opt.log](https://github.com/user-attachments/files/18726130/pv_opt.log)
[error.log](https://github.com/user-attachments/files/18726129/error.log)

**Comment by stevebuk1** [comment]
Your first log shows Appdaemon has rebooted Pv_opt at 21:38 and 00:38. 

When intitalising after the reboot, the inverter is not being found and PV_opt then stops with an error. 

The 2nd log shows exactly the same - reboots at 21:38 and 00:38. 

Theres no Pv_opt errors associated with the 21:38 and 00:38 reboots. 

You are running a 30 minute optimiser frequency which is running on the hour and 30 minutes past the hour, these are completing ok.

The tariff comparison function usually runs at 58 minutes past the hour, once per hour. 
I don't think its that, but I'm suspicious because of it being 8 minutes past something. 

Are you running tariff comparison? 

Can you post main.log (might be called appdaemon.log) to see what Appdaemon is doing?

**Comment by stevebuk1** [comment]
Also, your log shows Pv_opt is in readonly mode. In readonly mode, Pv_opt won't look for the inverter. 

If you can include a log with Pv_opt with Readonly off, this will help diagnose the problem. 

(I'm also using the alienatedsec Waveshare based solution so should be able to replicate any issues)

**Comment by ThomasPrior** [comment]
One main.log as requested. 
[main.log](https://github.com/user-attachments/files/18740851/main.log)

Am I running tariff comparison? Not sure what you mean here, can you clarify for a tired moron?

I've kept PV Opt in read only since switching from Agile to Go. I can turn it on for a bit, just turned it off as I had read the inverters have limited writes available and there have been occasions like this where I've woken up to a flat battery as the charge never got scheduled with PV Opt in a stuck state.

**Comment by stevebuk1** [comment]
Thanks for the log, will take a look.

> Am I running tariff comparison? Not sure what you mean here, can you clarify for a tired moron?

Sorry. Its the last 13 lines of config.yaml. There is an option to log costs of different tariffs for comparison, these output to the dashboard and the log. I've got them switched off and there were problems with it in the initial v4.0.0 release. Disable it by commenting out the last 13 or so lines starting with "alt_tarriffs". Commenting out means the first character is #, as below

```
#  alt_tariffs:
#    - name: Agile_Fix
#      octopus_import_tariff_code: E-1R-AGILE-23-12-06-G
#      octopus_export_tariff_code: E-1R-OUTGOING-FIX-12M-19-05-13-G
#
#    - name: Eco7_Agile
#      octopus_import_tariff_code: E-2R-VAR-22-11-01-G
#      octopus_export_tariff_code: E-1R-AGILE-OUTGOING-19-05-13-G
#
#    - name: Eco7_Fix
#      octopus_import_tariff_code: E-2R-VAR-22-11-01-G
#      octopus_export_tariff_code: E-1R-OUTGOING-FIX-12M-19-05-13-G
#      
#    - name: Flux
#      octopus_import_tariff_code: E-1R-FLUX-IMPORT-23-02-14-G
#      octopus_export_tariff_code: E-1R-FLUX-EXPORT-23-02-14-G

```

**Comment by ThomasPrior** [comment]
In that case no, I didn't know that was there but that is something I'd be interested in seeing the data for.

**Comment by stevebuk1** [comment]
> One main.log as requested.
> [main.log](https://github.com/user-attachments/files/18740851/main.log)

Upon Appdaemon reboot, it seems to be having a problem loading one of the PV_opt files (solis.py).
Can you attach config.yaml please?

**Comment by ThomasPrior** [comment]
Can't attach it as the filetype isn't allowed, but here's the contents:

```
# Internal configuration --- DO NOT EDIT ---
pvpy:
  module: pvpy
  global: true

inverters:
  module: inverters
  global: true

pv_opt:
  module: pv_opt
  class: PVOpt
  dependencies:
    - pvpy
    - solis

  log: pv_opt_log
  prefix: pvopt

# User configuration ---  EDIT AWAY! ---

  inverter_type: "SOLIS_SOLAX_MODBUS"
  # inverter_type: "SOLIS_CORE_MODBUS"#
  # inverter_type: SOLIS_SOLARMAN
  device_name: solis
  #consumption_history_days: 30

  # ========================================
  # Plant parameters
  # ========================================

  # All parameters can be a number or point to an entity UNLESS they start with 'id_'. All of
  # these are required but will be defaulted if not specified

  battery_capacity_wh: 16800
  # inverter_efficiency_percent: 97 # Default: 97
  # charger_efficiency_percent: 91 # Default: 91
  maximum_dod_percent: 10
  charger_power_watts: 5000
  inverter_power_watts: 5000
  # inverter_loss_watts: 100
  battery_current_limit_amps: 100
  
  # ========================================
  # Solcast configuration
  # ========================================
  #
  # id_solcast_today: sensor.solcast_pv_forecast_forecast_today
  # id_solcast_tomorrow: sensor.solcast_pv_forecast_forecast_tomorrow

  # ========================================
  # Solar and consumption forecast parameters
  # ========================================
  #
  # Valid options are:
  #
  # Solcast         - the Solcast mid-case forecast [Default]
  # Solcast_p90     - the Solcast high estimate
  # Solcast_p10     - the Solcast high estimate
  #
  # Set this using an "input_select" helper and it can be varied on the fly

  # solar_forecast:
  # - input_select.solar_forecast_source
  
  # # consumption estimation
  consumption_history_days:
    - 30
  # consumption_margin:
  #   - input_number.solar_opt_consumption_margin
  #  
  # ========================================
  # Octopus account parameters
  # ========================================

  # octopus_auto: False # Read tariffs from the Octopus Energy integration. If successful this over-rides the following parameters

  # octopus_account: !secret octopus_account
  # octopus_api_key: !secret octopus_api_key

  # The following Can be omitted if either of the above options is working correctly:

  # octopus_import_tariff_code: E-1R-GO-VAR-22-10-14-A
  # octopus_export_tariff_code: E-1R-OUTGOING-FIX-12M-19-05-13-A

  #octopus_import_tariff_code: E-1R-AGILE-23-12-06-A
  #octopus_export_tariff_code: E-1R-OUTGOING-FIX-12M-19-05-13-A
  
  # ===============================================================================================================
  # Brand / Integration Specific Config: SOLIS_SOLAX_MODBUS: https://github.com/wills106/homeassistant-solax-modbus
  # ===============================================================================================================
  #
  # These are the default entities used with the Solis Solax Modbus integration. You can change them here and over-ride the defaults

  # battery_voltage: sensor.{device_name}_battery_voltage
  # update_cycle_seconds: 300
  maximum_dod_percent: number.{device_name}_battery_minimum_soc 
  
  # id_consumption:
  #   - sensor.{device_name}_house_load
  #   - sensor.{device_name}_bypass_load

  # id_battery_soc: sensor.{device_name}_battery_soc
  # id_timed_charge_start_hours: number.{device_name}_timed_charge_start_hours
  # id_timed_charge_start_minutes: number.{device_name}_timed_charge_start_minutes
  # id_timed_charge_end_hours: number.{device_name}_timed_charge_end_hours
  # id_timed_charge_end_minutes: number.{device_name}_timed_charge_end_minutes
  # id_timed_charge_current: number.{device_name}_timed_charge_current

  # id_timed_discharge_start_hours: number.{device_name}_timed_discharge_start_hours
  # id_timed_discharge_start_minutes: number.{device_name}_timed_discharge_start_minutes
  # id_timed_discharge_end_hours: number.{device_name}_timed_discharge_end_hours
  # id_timed_discharge_end_minutes: number.{device_name}_timed_discharge_end_minutes
  # id_timed_discharge_current: number.{device_name}_timed_discharge_current

  # id_timed_charge_discharge_button: button.{device_name}_update_charge_discharge_times
  # id_inverter_mode: select.{device_name}_energy_storage_control_switch

  # ==============================================================================================================
  # Brand / Integration Specific Config: SOLIS_CORE_MODBUS: https://github.com/fboundy/ha_solis_modbus
  # ==============================================================================================================
  #
  # These are the default entities used with the Solis Core Modbus integration. You can change them here and over-ride the defaults

  # modbus_hub: "{device_name}"
  # modbus_slave: 1
  # battery_voltage: sensor.{device_name}_battery_voltage
  # maximum_dod_percent: sensor.{device_name}_overdischarge_soc
  # update_cycle_seconds: 60
  # id_consumption_today: sensor.{device_name}_house_load_today
  # id_consumption:
  #   - sensor.{device_name}_house_load_power
  #   - sensor.{device_name}_backup_load_power

  # id_grid_power: sensor.{device_name}_grid_active_power
  # id_inverter_ac_power: sensor.{device_name}_inverter_ac_power
  # id_battery_soc: sensor.{device_name}_battery_soc

  # id_timed_charge_start_hours: sensor.{device_name}_timed_charge_start_hour
  # id_timed_charge_start_minutes: sensor.{device_name}_timed_charge_start_minute
  # id_timed_charge_end_hours: sensor.{device_name}_timed_charge_end_hour
  # id_timed_charge_end_minutes: sensor.{device_name}_timed_charge_end_minute
  # id_timed_charge_current: sensor.{device_name}_timed_charge_current_limit

  # id_timed_discharge_start_hours: sensor.{device_name}_timed_discharge_start_hour
  # id_timed_discharge_start_minutes: sensor.{device_name}_timed_discharge_start_minute
  # id_timed_discharge_end_hours: sensor.{device_name}_timed_discharge_end_hour
  # id_timed_discharge_end_minutes: sensor.{device_name}_timed_discharge_end_minute
  # id_timed_discharge_current: sensor.{device_name}_timed_discharge_current_limit

  # id_inverter_mode: sensor.{device_name}_energy_storage_control_switch

  # ==============================================================================================================
  # Brand / Integration Specific Config: SOLIS_SOLARMAN: https://github.com/StephanJoubert/home_assistant_solarman
  # ==============================================================================================================
  #
  # These are the default entities used with the Solis Solarman integration. You can change them here and over-ride the defaults

  # battery_voltage: sensor.{device_name}_battery_voltage
  # maximum_dod_percent: 12
  # update_cycle_seconds: 300
  
  # id_consumption:
  #   - sensor.{device_name}_house_load_power
  #   - sensor.{device_name}_backup_load_power

  # id_grid_power: sensor.{device_name}_meter_active_power
  # id_inverter_ac_power": sensor.{device_name}_inverter_ac_power
  # id_battery_soc: sensor.{device_name}_battery_soc
  # id_backup_mode_soc: 

  # id_timed_charge_start_hours: sensor.{device_name}_timed_charge_start_hour
  # id_timed_charge_start_minutes: sensor.{device_name}_timed_charge_start_minute
  # id_timed_charge_end_hours: sensor.{device_name}_timed_charge_end_hour
  # id_timed_charge_end_minutes: sensor.{device_name}_timed_charge_end_minute
  # id_timed_charge_current: sensor.{device_name}_timed_charge_current

  # id_timed_discharge_start_hours: sensor.{device_name}_timed_discharge_start_hour
  # id_timed_discharge_start_minutes: sensor.{device_name}_timed_discharge_start_minute
  # id_timed_discharge_end_hours: sensor.{device_name}_timed_discharge_end_hour
  # id_timed_discharge_end_minutes: sensor.{device_name}_timed_discharge_end_minute
  # id_timed_discharge_current: sensor.{device_name}_timed_discharge_current

  # id_inverter_mode: sensor.{device_name}_storage_control_mode

```
