### ISSUE TITLE
Flux charging periods seem to be ignored in favour of peak rate charging

### ISSUE THREAD

**Issue by ThomasPrior** [stevebuk1/pv_opt#52]
**Describe the bug**

Octopus flux customer, cheap rates between 02:00 and 05:00 daily.

PV_OPT seems to be wanting to charge 3500W between 00:00 and 00:30 at a higher rate, rather than wait for the cheap period at 02:00

**Expected behavior**
I would have thought the optimum approach on Flux to be to consume from the grid when the battery is discharged until the cheaper period starts at 02:00.

**Screenshots**

<img width="1239" alt="pv_opt" src="https://github.com/fboundy/pv_opt/assets/34111848/17521034-bd5a-46d8-a6e3-f141a8b40bc3">

**Additional context**
Logs: 
[pv_opt.log](https://github.com/fboundy/pv_opt/files/13675172/pv_opt.log)

pv_opt config:

```
# Internal configuration --- DO NOT EDIT ---
pvpy:
  module: pvpy
  global: true

inverters:
  module: inverters
  global: true

pv_opt:
  module: pv_opt
  class: PVOpt
  log: pv_opt_log
  prefix: pvopt
  inverter_type: "SOLIS_SOLAX_MODBUS"
  # inverter_type: "SOLIS_CORE_MODBUS"

  # User configuration ---  EDIT AWAY! ---

  # ========================================
  # Plant parameters
  # ========================================

  # All parameters can be a number or point to an entity UNLESS they start with 'id_'. All of
  # these are required but will be defaulted if not specified

  battery_capacity_Wh: 9400
  # inverter_efficiency_percent: 97 # Default: 97
  # charger_efficiency_percent: 91 # Default: 91
  maximum_dod_percent: 12
  charger_power_watts: 3500
  inverter_power_watts: 5000
  # inverter_loss_watts: 100
  battery_voltage: sensor.solis_battery_voltage
  
  # ========================================
  # Solcast configuration
  # ========================================
  #
  # id_solcast_today: sensor.solcast_pv_forecast_forecast_today
  # id_solcast_tomorrow: sensor.solcast_pv_forecast_forecast_tomorrow

  # ========================================
  # Solar and consumption forecast parameters
  # ========================================
  #
  # Valid options are:
  #
  # Solcast         - the Solcast mid-case forecast [Default]
  # Solcast_p90     - the Solcast high estimate
  # Solcast_p10     - the Solcast high estimate
  #
  # Set this using an "input_select" helper and it can be varied on the fly

  # solar_forecast:
  # - input_select.solar_forecast_source
  #   - Solcast

  # # consumption estimation
  # consumption_history_days:
  #   - 7
  # consumption_margin:
  #   - input_number.solar_opt_consumption_margin
  #  
  # ========================================
  # Octopus account parameters
  # ========================================

  octopus_auto: True # Read tariffs from the Octopus Energy integration. If successful this over-rides the following parameters

  octopus_account: !secret octopus_account
  octopus_api_key: !secret octopus_api_key

  # The following Can be omitted if either of the above options is working correctly:

  octopus_import_tariff_code: E-1R-FLUX-IMPORT-23-02-14-A
  octopus_export_tariff_code: E-1R-FLUX-EXPORT-23-02-14-A

  # octopus_import_tariff_code: E-1R-FLUX-IMPORT-23-02-14-G
  # octopus_export_tariff_code: E-1R-FLUX-EXPORT-23-02-14-G
  
  # ===============================================================================================================
  # Brand / Integration Specific Config: SOLIS_SOLAX_MODBUS: https://github.com/wills106/homeassistant-solax-modbus
  # ===============================================================================================================
  #
  # These are the default entities used with the Solis Solax Modbus integration. You can change them here and over-ride the defaults

  battery_voltage: sensor.solis_battery_voltage

  id_consumption:
    - sensor.solis_house_load
    - sensor.solis_bypass_load

  id_battery_soc: sensor.solis_battery_soc
  id_timed_charge_start_hours: number.solis_timed_charge_start_hours
  id_timed_charge_start_minutes: number.solis_timed_charge_start_minutes
  id_timed_charge_end_hours: number.solis_timed_charge_end_hours
  id_timed_charge_end_minutes: number.solis_timed_charge_end_minutes
  id_timed_charge_current: number.solis_timed_charge_current

  id_timed_discharge_start_hours: number.solis_timed_discharge_start_hours
  id_timed_discharge_start_minutes: number.solis_timed_discharge_start_minutes
  id_timed_discharge_end_hours: number.solis_timed_discharge_end_hours
  id_timed_discharge_end_minutes: number.solis_timed_discharge_end_minutes
  id_timed_discharge_current: number.solis_timed_discharge_current

  id_timed_charge_discharge_button: button.solis_update_charge_discharge_times
  id_inverter_mode: select.solis_energy_storage_control_switch

  # ==============================================================================================================
  # Brand / Integration Specific Config: SOLIS_CORE_MODBUS: https://github.com/fboundy/ha_solis_modbus
  # ==============================================================================================================
  #
  # These are the default entities used with the Solis Core Modbus integration. You can change them here and over-ride the defaults

  # modbus_hub: solis
  # modbus_slave: 1
  # battery_voltage: sensor.solis_battery_voltage
  # maximum_dod_percent: sensor.solis_overdischarge_soc
  #
  # id_consumption:
  #   - sensor.solis_house_load_power
  #   - ensor.solis_backup_load_power

  # id_grid_power: sensor.solis_grid_active_power
  # id_inverter_ac_power": sensor.solis_inverter_ac_power
  # id_battery_soc: sensor.solis_battery_soc

  # id_timed_charge_start_hours: sensor.solis_timed_charge_start_hour
  # id_timed_charge_start_minutes: sensor.solis_timed_charge_start_minute
  # id_timed_charge_end_hours: sensor.solis_timed_charge_end_hour
  # id_timed_charge_end_minutes: sensor.solis_timed_charge_end_minute
  # id_timed_charge_current: sensor.solis_timed_charge_current_limit

  # id_timed_discharge_start_hours: sensor.solis_timed_discharge_start_hour
  # id_timed_discharge_start_minutes: sensor.solis_timed_discharge_start_minute
  # id_timed_discharge_end_hours: sensor.solis_timed_discharge_end_hour
  # id_timed_discharge_end_minutes: sensor.solis_timed_discharge_end_minute
  # id_timed_discharge_current: sensor.solis_timed_discharge_current_limit

  # id_timed_charge_discharge_button: button.solis_update_charge_discharge_times
  # id_inverter_mode: select.solis_energy_storage_control_switch

```
